# Generated by Django 3.0.8 on 2020-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_error_category', models.FileField(blank=True, null=True, upload_to='')),
                ('http_response_code', models.DateTimeField(auto_now_add=True)),
                ('http_response_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['http_response_code'],
            },
        ),
    ]
