# Generated by Django 3.0.8 on 2020-07-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicodes', '0003_apicodes_api_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicodes',
            name='http_response_code',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
