# Generated by Django 3.0.8 on 2020-08-20 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transmissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerErrorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=256)),
                ('clean', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transmissions.Transmission')),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployerError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('employerid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('errorfield', models.CharField(max_length=256)),
                ('error_description', models.CharField(max_length=256)),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errored_employers', to='transmissions.Transmission')),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('FederalEmployerIdentificationNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('CarrierMasterAgreementNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(max_length=256)),
                ('address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('Choose state', 'Choose state'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='Choose state', max_length=100)),
                ('zipcode', models.CharField(max_length=256)),
                ('employer_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('purpose', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('backend_SOR_connection', models.CharField(default='Disconnected', max_length=255)),
                ('commit_indicator', models.CharField(default='Not Committed', max_length=255)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('bulk_upload_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_set', to='transmissions.Transmission')),
            ],
            options={
                'ordering': ['-employer_date'],
            },
        ),
    ]
