# Generated by Django 3.0.8 on 2020-09-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20200823_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='transmissionid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
