# Generated by Django 3.0.8 on 2020-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employer_transmissionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='planadmin_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
