# Generated by Django 3.0.8 on 2020-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employer_planadmin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employererror',
            name='sendername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employererror',
            name='transmissionid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employererroraggregate',
            name='execution_time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employererroraggregate',
            name='volume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
