# Generated by Django 3.0.8 on 2020-09-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0005_auto_20200911_1722'),
        ('employers', '0010_auto_20200911_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='transmission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer_set', to='transmissions.Transmission'),
            preserve_default=False,
        ),
    ]
