# Generated by Django 3.0.8 on 2020-09-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0005_auto_20200911_1722'),
        ('employers', '0011_auto_20200924_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_set', to='transmissions.Transmission'),
        ),
    ]
