# Generated by Django 3.0.8 on 2020-08-20 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeErrorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=256)),
                ('clean', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.Employer')),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('employeeid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('errorfield', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errored_employees', to='employers.Employer')),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=255, null=True)),
                ('ssn', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('gendercode', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=0)),
                ('birthdate', models.DateField()),
                ('maritalstatus', models.CharField(max_length=255)),
                ('home_address_line_1', models.CharField(max_length=256)),
                ('home_address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('home_city', models.CharField(max_length=256)),
                ('home_state', models.CharField(choices=[('Choose state', 'Choose state'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='Choose state', max_length=100)),
                ('home_zipcode', models.CharField(max_length=256)),
                ('mail_address_line_1', models.CharField(blank=True, max_length=256, null=True)),
                ('mail_address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('mail_city', models.CharField(blank=True, max_length=256, null=True)),
                ('mail_state', models.CharField(choices=[('Choose state', 'Choose state'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='Choose state', max_length=100)),
                ('mail_zipcode', models.CharField(blank=True, max_length=256, null=True)),
                ('work_address_line_1', models.CharField(blank=True, max_length=256, null=True)),
                ('work_address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('work_city', models.CharField(blank=True, max_length=256, null=True)),
                ('work_state', models.CharField(choices=[('Choose state', 'Choose state'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='Choose state', max_length=100)),
                ('work_zipcode', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('enrollment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_information', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_date', models.DateTimeField(auto_now=True)),
                ('sms', models.CharField(blank=True, max_length=256, null=True)),
                ('emailer', models.CharField(blank=True, max_length=256, null=True)),
                ('artefact', models.FileField(blank=True, default='intellidatastatic.s3.amazonaws.com/media/default.png', null=True, upload_to='')),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('backend_SOR_connection', models.CharField(default='Disconnected', max_length=255)),
                ('commit_indicator', models.CharField(max_length=255)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('bulk_upload_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_set', to='employers.Employer')),
            ],
            options={
                'ordering': ['-employee_date'],
            },
        ),
    ]
