# Generated by Django 3.0.8 on 2020-08-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20200823_0120'),
        ('employees', '0003_auto_20200823_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_set', to='employers.Employer'),
            preserve_default=False,
        ),
    ]
