# Generated by Django 3.0.8 on 2020-08-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20200823_0120'),
        ('employees', '0004_auto_20200823_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_set', to='employers.Employer'),
        ),
    ]
