# Generated by Django 3.0.8 on 2020-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20200823_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employerid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
