# Generated by Django 3.0.8 on 2020-09-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200902_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeerroraggregate',
            name='execution_time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employeeerroraggregate',
            name='volume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
