# Generated by Django 3.0.8 on 2020-09-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200911_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='execution_time',
            new_name='execution_time_for_this_run',
        ),
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='volume',
            new_name='volume_processed_in_this_run',
        ),
    ]
