# Generated by Django 3.0.8 on 2020-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20200911_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeerror',
            name='employerid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
