# Generated by Django 3.0.8 on 2020-09-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employeeerror_employerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='error',
            new_name='number_of_error_occurences',
        ),
    ]
