# Generated by Django 3.0.8 on 2020-09-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20200911_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='clean',
            new_name='processed_clean',
        ),
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='total',
            new_name='total_employees_received',
        ),
    ]
