# Generated by Django 3.0.8 on 2020-09-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20200911_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='total_employees_received',
            new_name='total_employees_till_date',
        ),
    ]
