# Generated by Django 3.0.8 on 2020-09-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20200911_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeerroraggregate',
            options={'ordering': ['-run_date']},
        ),
        migrations.RenameField(
            model_name='employeeerroraggregate',
            old_name='error_date',
            new_name='run_date',
        ),
    ]
