# Generated by Django 3.0.8 on 2020-08-20 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductErrorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=256)),
                ('clean', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('productid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('errorfield', models.CharField(max_length=256)),
                ('error_description', models.CharField(max_length=256)),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Unknown Type', 'Unknown Type'), ('LIFE', 'Life Insurance'), ('STD', 'Short Term Disability'), ('LTD', 'Long Term Disability'), ('CI', 'Critical Illness'), ('ACCIDENT', 'Accident'), ('ADND', 'Accidental Death & Dismemberment'), ('CANCER', 'Cancer'), ('DENTAL', 'DENTAL'), ('VISION', 'Vision'), ('HOSPITAL', 'Hospital;'), ('IDI', 'Individual Disability')], default='Unknown Type', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_1000_units', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('product_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('backend_SOR_connection', models.CharField(default='Disconnected', max_length=255)),
                ('commit_indicator', models.CharField(default='Not Committed', max_length=255)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('bulk_upload_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-product_date'],
                'unique_together': {('name', 'type', 'product_date')},
            },
        ),
    ]
