# Generated by Django 3.0.8 on 2020-07-15 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Unknown Type', 'Unknown Type'), ('LIFE', 'Life Insurance'), ('STD', 'Short Term Disability'), ('LTD', 'Long Term Disability'), ('CI', 'Critical Illness')], default='Unknown Type', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_1000_units', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('product_date', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-product_date'],
                'unique_together': {('name', 'type', 'product_date')},
            },
        ),
    ]
