# Generated by Django 3.0.8 on 2020-07-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uploaded_at',
        ),
    ]
