# Generated by Django 3.0.8 on 2020-09-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200823_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producterroraggregate',
            options={'ordering': ['-run_date']},
        ),
        migrations.RenameField(
            model_name='producterroraggregate',
            old_name='error_date',
            new_name='run_date',
        ),
    ]
