# Generated by Django 3.0.8 on 2020-07-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_tyransmissionpattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tyransmissionPattern',
            new_name='transmission_pattern',
        ),
    ]
