# Generated by Django 3.0.8 on 2020-07-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200722_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='transmission_pattern',
            new_name='system_of_record_syncup',
        ),
    ]
