# Generated by Django 3.0.8 on 2020-07-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200722_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='system_of_record_syncup',
            field=models.CharField(default='Disc', max_length=255),
        ),
    ]
