# Generated by Django 3.0.8 on 2020-07-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200722_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='system_of_record_syncup',
            field=models.CharField(default='Not Connected to SOR', max_length=255),
        ),
    ]
