# Generated by Django 3.0.8 on 2020-07-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200722_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='system_of_record_syncup',
            new_name='backend_SOR_connection',
        ),
    ]
