# Generated by Django 3.0.8 on 2020-07-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200723_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backend_SOR_connection_set_as',
            field=models.CharField(default='Disconnected', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='backend_SOR_connection',
            field=models.CharField(default='Disconnected', max_length=255),
        ),
    ]
