# Generated by Django 3.0.8 on 2020-07-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200723_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='backend_SOR_connection_set_as',
        ),
    ]
