# Generated by Django 3.0.8 on 2020-07-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_backend_sor_connection_set_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transaction_status',
            field=models.CharField(default='Success', max_length=255),
        ),
    ]
