# Generated by Django 3.0.8 on 2020-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
