# Generated by Django 3.0.8 on 2020-07-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200725_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commit_indicator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
