# Generated by Django 3.0.8 on 2020-07-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_commit_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commit_indicator',
            field=models.CharField(default='Not Committed', max_length=255),
        ),
    ]
