# Generated by Django 3.0.8 on 2020-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200726_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='transaction_status',
            new_name='response',
        ),
        migrations.AddField(
            model_name='product',
            name='record_status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
