# Generated by Django 3.0.8 on 2020-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200801_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='record_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
