# Generated by Django 3.0.8 on 2020-08-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200802_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
