# Generated by Django 3.0.8 on 2020-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200803_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
