# Generated by Django 3.0.8 on 2020-08-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200803_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulkuploadind',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
