# Generated by Django 3.0.8 on 2020-08-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_bulkuploadind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bulkuploadind',
            new_name='bulk_upload_indicator',
        ),
    ]
