# Generated by Django 3.0.8 on 2020-08-20 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionErrorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=256)),
                ('clean', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('transmissionid', models.CharField(blank=True, max_length=256, null=True)),
                ('SenderName', models.CharField(blank=True, max_length=256, null=True)),
                ('errorfield', models.CharField(max_length=256)),
                ('error_description', models.CharField(max_length=256)),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmissionid', models.CharField(blank=True, max_length=255, null=True)),
                ('SenderName', models.CharField(blank=True, max_length=255, null=True)),
                ('BenefitAdministratorPlatform', models.CharField(blank=True, max_length=255, null=True)),
                ('ReceiverName', models.CharField(blank=True, max_length=255, null=True)),
                ('TestProductionCode', models.CharField(blank=True, max_length=255, null=True)),
                ('TransmissionTypeCode', models.CharField(default='Electronic', max_length=255)),
                ('SystemVersionIdentifier', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('backend_SOR_connection', models.CharField(default='Disconnected', max_length=255)),
                ('commit_indicator', models.CharField(default='Not Committed', max_length=255)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('bulk_upload_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
