# Generated by Django 3.0.8 on 2020-08-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transmissionerror',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transmissionerroraggregate',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
