# Generated by Django 3.0.8 on 2020-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0002_auto_20200823_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='SenderName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
