# Generated by Django 3.0.8 on 2020-09-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmissions', '0003_auto_20200901_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='planadmin_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
