# Generated by Django 3.0.8 on 2020-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emailer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sms',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
