# Generated by Django 3.0.8 on 2020-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200720_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='backend_SOR_connection',
            field=models.CharField(default='Disconnected', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='bulk_upload_indicator',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='commit_indicator',
            field=models.CharField(default='Not Committed', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='record_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
