# Generated by Django 3.0.8 on 2020-08-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200814_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='artefact',
            field=models.FileField(blank=True, default='intellidatastatic.s3.amazonaws.com/media/default.png', null=True, upload_to=''),
        ),
    ]
