# Generated by Django 3.0.8 on 2020-08-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_membererror_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membererror',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='membererror',
            name='errorfield',
            field=models.CharField(max_length=256),
        ),
    ]
