# Generated by Django 3.0.8 on 2020-08-17 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_photo'),
        ('members', '0010_auto_20200817_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membererror',
            options={'ordering': ['-error_date']},
        ),
        migrations.AlterField(
            model_name='membererror',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group'),
        ),
        migrations.CreateModel(
            name='MemberErrorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=256)),
                ('clean', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errored_members', to='groups.Group')),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
    ]
