# Generated by Django 3.0.8 on 2020-08-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_photo'),
        ('members', '0011_auto_20200817_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membererror',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errored_members', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='membererroraggregate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group'),
        ),
    ]
