# Generated by Django 3.0.8 on 2020-08-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200817_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='membererror',
            name='memberid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='membererror',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
