# Generated by Django 3.0.8 on 2020-08-23 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(blank=True, max_length=255, null=True)),
                ('EventTypeCode', models.CharField(blank=True, max_length=255, null=True)),
                ('EventTypeReason', models.CharField(blank=True, max_length=255, null=True)),
                ('EventDate', models.DateTimeField(auto_now=True)),
                ('TransactionDate', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('backend_SOR_connection', models.CharField(default='Disconnected', max_length=255)),
                ('commit_indicator', models.CharField(default='Not Committed', max_length=255)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('bulk_upload_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-EventDate'],
            },
        ),
    ]
