# Generated by Django 3.0.8 on 2020-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventSubjectId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTypeCode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
