# Generated by Django 3.0.8 on 2020-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200823_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventTypeCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
