# Generated by Django 3.0.8 on 2020-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200823_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventSubjectName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
