# Generated by Django 3.0.8 on 2020-09-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandatories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandatory',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='mandatory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
